# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'CoOp.sln'
  buildConfiguration: 'Release'
  testProjectsFilter: 'CoOp.*/*.Tests.csproj'
  targetPlatform: 'win-x64'
  artifactName: 'coOpWebArtifact'

steps:
    - task: UseDotNet@2 
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk
    - script: dotnet build $(solution) --configuration $(buildConfiguration)
      displayName: 'dotnet build $(solution) $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        command: test
        projects: '$(testProjectsFilter)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r $(targetPlatform) --self-contained false --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(artifactName)'



